name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your GitHub code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # use your Node version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build Next.js
      - name: Build Next.js Project
        run: npm run build

      # Step 5: Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 54.91.79.24                   # your EC2 IP
          username: ubuntu                     # your EC2 username
          key: ${{ secrets.PRIVATE_KEY }}     # private key stored in GitHub secrets
          port: 22
          script: |
            cd learncicd         # your project folder on EC2
            git pull origin main
            npm ci
            npm run build
            pm2 start npm --name "nextjs-app" -- run start -- -p 3000

